---
title: "Shiny App Presentation"  
author: "Xia Wenwen"  
date: "6/8/2022"  
output: slidy_presentation
---

```{r setup, include=FALSE}
library(ggplot2)
knitr::opts_chunk$set(echo = FALSE)
```

## Introduction

The Shiny application shows the predictions of MPG based on the weight and cylinder in mtcars dataset.  

The 1st model is the linear model of mpg over wt, where wt is the weight in 1000 lbs.  

The 2nd model is the linear model of mpg over wt and cyl, where cyl is the number of cylinders with selection of value 4, 6 or 8.  

## Data and Models
```{r cars, echo = TRUE}
head(mtcars)
model1 <- lm(mpg ~ wt, data = mtcars)
model2 <- lm(mpg ~ wt + as.factor(cyl), data = mtcars)
```

## Model 1 Plot
```{r model1, echo = FALSE}
plot(mtcars$wt, mtcars$mpg, xlab = "Weight (1000 lbs)", 
             ylab = "Miles/(US) gallon", bty = "n", pch = 16, 
             xlim = c(1.5, 6), ylim = c(10, 35))

abline(model1, col = "red", lwd = 2)
```

## Model 2 Plot
```{r model2, echo = FALSE, message = FALSE}
g <- ggplot(data = mtcars, aes(x=wt, y=mpg, group=cyl, color=as.factor(cyl))) +
            geom_point() + geom_smooth(method = "lm")
g
```
